### ISSUE TITLE
Making sense of configuration and service handling

### ISSUE THREAD

**Issue by ztombol** [evgeni/hdapsd#8]
*This issue may seem a bit loaded, touching on systemd, udev and configuration, but the problems are related and can only be solved together. I intend this issue to be a starting point for discussion on these observations.*

# Overview

I installed `hdapsd` and found that:
  1. its behaviour is probably not what most users would expect or want, and
  2. configuration is difficult

In the followings I describe the issues involved and the proposed solutions.

# 1. Behaviour

## Issue

The installed udev rule causes all disks to be automatically protected by launching a daemon for each disk using `hdapsd@.service`. This happens for external disks too. Every time one is connected a new process is launched only to fail, as these disk do not support head unload on command (only via APM, as far as I know). There is no easy way of excluding disks.

I think this automatic behaviour has little value as most users have only one or two disks to protect, and manually adjusting settings (e.g. fine tuning `--sensitivity`) is *always* desired.

## Solution

Removing the udev rule turns off the automatic behaviour, however configuration still remains difficult. See the next section.

Required modifications:
  - removing `hdapsd.rules`

# 2. Configuration

## Issue

There is a built-in configuration system implemented with `libconfig`, but it does not seem to be used (the configuration file is not installed either).

The only way to change settings is by overwriting parts or the whole service file in `/etc/systemd/system/`. Users unfamiliar with systemd will find this difficult.

### Using `libconfig`

The built-in `libconfig` based configuration provides a simple way to modify setting in `/etc/hdapsd.conf`. Since configuration specified this way applies to all protected disks, it is sufficient to run a single daemon process using `hdapsd.service`, instead of one for each disk with `hdapsd@.service`.

**Note** that `pidfile`, `syslog` and `background` should be removed from the configuration file as these have to be set in the service file for systemd to work properly. See *systemd.service(5)* for more.

Required modifications:
  - slight modification to `hdapsd.service`
  - removing `hdapsd@.service`
  - installing `hdapsd.conf` to `/etc`
  - removing some options from the config file

## Using `EnvironmentFile`

Using the `EnvironmentFile` option in the service file to read command line arguments to `hdapsd` from a file and append them to `ExecStart`. This is what `smartd` does. See *systemd.exec(5)* for more.

/etc/conf.d/hdpasd

    HDAPSD_ARGS='--sensitivity 40 --device=/dev/disk/by-id/ata-HTS541040G9AT00'

hdapsd.service (excerpt)

    [Service]
    EnvironmentFile=/etc/conf.d/hdpasd
    ExecStart=/usr/sbin/hdapsd --pidfile --background --syslog $HDAPSD_ARGS

Required modifications:
  - slight modification of `hdapsd.service`
  - removing `hdapsd@.service`
  - installing an environment file to `/etc/conf.d`

## Using systemd local configuration

It is possible to overwrite a service file in part or entirely by adding a local configuration in `/etc/systemd/system`.

/usr/lib/systemd/system/hdapsd.service (excerpt)

    ExecStart=/usr/sbin/hdapsd --pidfile --background --syslog --adaptive

/etc/systemd/system/hdapsd.service (excerpt)

    # The empty assignment resets the option, see systemd.exec(5)
    ExecStart=
    ExecStart=/usr/sbin/hdapsd --pidfile --background --syslog --sensitivity 40 --device /dev/sda

This technique can be used with `hdapsd@.service` as well to provide per disk configuration (if that is desired).

# Summary

The configuration side of the issue really depends on the level of control you want to have (global and/or per disk configuration) and the preferred way of configuration (libconfig or environment file, and/or systemd).

On the behaviour side of the issue. If I'm wrong and there is a legitimate reason for keeping udev in the loop, some other solution have to be found for easing configuration and excluding disks.

I tried to be as concise as possible while still being clear about the approach of each proposed solution. Of course I would be happy to contribute code if you find that some of these modifications are necessary.

If you are still reading, thank you and give yourself a pat on the back!

Thank you for maintaining `hdapsd`!

**Comment by evgeni** [comment]
I'll close here, as there was no further input. Feel free to reopen.
